import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import { TooltipProvider } from "@/components/ui/tooltip";
import { SidebarApp } from "@/components/layout/sidebar";
import { TopBarApp } from "@/components/layout/topbar";
import { ResizablePanelLayout } from "@/components/layout/resizable-layout";
import { SidebarInset, SidebarProvider } from "@/components/ui/sidebar";
import { PanelProvider } from "@/hooks/use-panel";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head />
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <TooltipProvider>
            <PanelProvider>
              <SidebarProvider>
                <SidebarApp />
                <SidebarInset>
                  <TopBarApp />
                  <ResizablePanelLayout>{children}</ResizablePanelLayout>
                </SidebarInset>
              </SidebarProvider>
            </PanelProvider>
          </TooltipProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
